name: Build & Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # 🔐 Login Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # 🐳 Build frontend
    - name: Build frontend image
      run: |
        docker build -t keyn1990/bankflay-frontend:latest .

    # 🚀 Push
    - name: Push frontend image
      run: |
        docker push keyn1990/bankflay-frontend:latest

    # 🖥 Deploy VPS
    - name: Deploy via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: 192.67.197.185
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          set -e

          cd /root/bankflay

          echo "🚨 STOP old containers"
          docker-compose down || true

          echo "🧹 CLEAN dangling images"
          docker image prune -f || true

          echo "⬇️ PULL new images"
          docker-compose pull

          echo "🚀 START new containers"
          docker-compose up -d

          echo "🔍 STATUS"
          docker ps
